name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  typescript:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: linting typescript
        run: npm run lint:ts

  scss:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        if: always()
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: screenshot testing
        run: npm run test:ui:ci
        if: always()

  # testing:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [17.x]
  #   steps:
  #     - name: Cache deps
  #       uses: actions/cache@v2
  #       with:
  #         path: ~/.npm
  #         key: node-modules-${{ hashFiles('**/package-lock.json') }}
  #     - uses: actions/checkout@v2
  #     - name: Starting Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: install modules
  #       run: npm ci
  #     - name: unit testing
  #       run: npm run test:unit

  # storybook:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [17.x]
  #   steps:
  #     - name: Cache deps
  #       uses: actions/cache@v2
  #       with:
  #         path: ~/.npm
  #         key: node-modules-${{ hashFiles('**/package-lock.json') }}
  #     - uses: actions/checkout@v2
  #     - name: Starting Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: install modules
  #       run: npm ci
  #     - name: build production project
  #       run: npm run build:prod
  #     - name: build storybook
  #       run: npm run storybook:build
  #     - name: screenshot testing
  #       run: npm run test:ui:ci
